(function(w) {
  'use strict';

  var metaPool = [
["firewall1","Firewall - IPTables","January 21, 2013",""],
["install-and-configure-vpn-ssh-tunneling","How to install and configure VPN network and SSH tunneling","June 06, 2013",""],
["set-up-local-proxy-server-to-filter-all-traffic","Set up local proxy server which will filter all the traffic","June 25, 2013",""],
["tor-privoxy-anonymous","Tor + Privoxy = anonymous cached browsing","June 25, 2013",""],
["honeypot","Catch the bad guys with honeypot","June 26, 2013",""],
["couldnot-resolve-host","CentOS: Couldn't resolve host 'mirrorlist.centos.org'","June 27, 2013",""],
["encrypt-files-with-openssl","Encrypt your files with openssl","June 28, 2013","encrypt"],
["owncloud-with-ssl-and-nginx","Install ownCloud with SSL and Nginx on your CentOS server","June 29, 2013",""],
["fedora-xfce-customization","Fedora XFCE Customization - from ugly to eyecandy","July 05, 2013",""],
["blog_converted","Blog converted","July 26, 2013",""],
["useful-bash-scripts","Useful dead simple bash scripts","July 26, 2013",""],
["5th-day-with-python","It's 5th day since I started to learn Python","July 30, 2013",""],
["xfce-kwin","Xfce + Kwin = eyecandy combination","August 10, 2013",""],
["my-project","My little project has been created","August 25, 2013",""],
["two-months","Two months...","October 10, 2013",""],
["xfce-to-kde","Switching from XFCE to KDE without re-install","October 18, 2013","archlinux"],
["new_year_new_challenges","New Year, New Challenges","January 01, 2014",""],
["whats_new","What's new","January 24, 2014",""],
["change-file-format-to-all-files","Change the file format to all files in a directory","January 30, 2014",""],
["archlinux-installation","Tutorial: Archlinux installation","February 13, 2014","archlinux"],
["extend_your_wireless_coverage","One house, one router, two floors, weak wireless","March 30, 2014",""],
["blogfy-reborn","Blogfy - reborn","April 06, 2014",""],
["bad_archey","GRUB - dual booting issue","April 11, 2014","archlinux"],
["set_grub_theme_and_distro_name","GRUB hacking","April 11, 2014",""],
["setting_up_plymouth","Setting up Plymouth","April 12, 2014",""],
["installing_python_in_android","Install python3 in any android device","April 30, 2014",""],
["vlc-python-screencast-pastbin-server","Pastebin-like server in python, vlc screecast and snapshots","May 10, 2014","encrypt"],
["best-compression-tools","The best data compression tool","May 11, 2014",""],
["firewall2","TCP/IP stack hardening","May 17, 2014",""],
["tp-link-backdoor","TP-LINK devices with built-in backdoors","May 18, 2014",""],
["fix-that-flat-app","Got flat applications, let's make them eyecandy","May 24, 2014",""],
["install-owncloud-v2","Install Owncloud in CentOS (version 2)","May 24, 2014",""],
["btsync","Bittorrent Sync installation","May 31, 2014",""],
["owncloud-with-ssl-and-nginx-version2","Install ownCloud with SSL and Nginx in CentOS (version 3)","June 05, 2014",""],
["encrypted-emails","Thunderbird + GnuPG + Enigmail = encrypted email conversation","June 08, 2014","encrypt,gpg"],
["best-png-compression-tool","The best PNG compression tool","June 01, 2014",""],
["fsck-failed","OpenBSD - fsck failed","June 14, 2014","bsd"],
["kde-to-openbox","Switching from KDE to Openbox","June 28, 2014",""],
["wtf","Why the website went down","July 02, 2014",""],
["secure_backups","GPG encrypted backups","July 05, 2014","encrypt,gpg"],
["gpg-use-stronger-algorithms","GPG - use stronger algorithms","July 12, 2014","gpg"],
["thunderbird_strip_email_headers","Thunderbird - strip your email headers","July 19, 2014","gpg"],
["incremental-backups","Incremental backups","July 24, 2014",""],
["gentoo-minimal-installation","Gentoo - minimal installation","August 09, 2014","gentoo"],
["mutt","Everyone - ditch Thunderbird !","August 16, 2014",""],
["whats_new_2","What's new 2","September 26, 2014",""],
["running_out_of_ram","Running out of ram ?","October 11, 2014",""],
["dust_off_your_pc","Dust off your pc","November 21, 2014",""],
["split_file_and_session","Split large file and","December 13, 2014",""],
["random_post","Random post","January 17, 2015",""],
["contributions","Recent contributions","February 20, 2015",""],
["openbox-to-dwm","Switching from Openbox to dwm","February 25, 2015",""],
["dns_cache","Dead simple DNS caching","March 11, 2015",""],
["dns_encryption","DNS encryption","March 12, 2015","encrypt"],
["dm_crypt_luks","DM-Crypt LUKS encrypted partition","May 01, 2015","encrypt,luks"],
["random_post_2","Random post 2","March 16, 2015",""],
["install_arch_with_full_disk_encryption","Install Arch with full disk encryption","March 23, 2015","encrypt,luks,archlinux"],
["encrypted_emails2","Encrypted emails part 1 of 2","May 02, 2015","gpg"],
["encrypted_emails3","Encrypted emails part 2 of 2","June 02, 2015","gpg"],
["boot_loader_encryption","Boot loader encryption","June 20, 2015","encrypt"],
["torchlight2_segfaults","Torchlight 2 segfaults","July 14, 2015",""],
["encrypted_chat_with_otr","Encrypted chat with OTR","July 31, 2015","encrypt"],
["random_cpu_spikes","Random CPU spikes","August 01, 2015",""],
["custom_repo_with_signed_packages","Custom repo with signed packages","August 15, 2015","archlinux"],
["dwm_to_xmonad","Switching from dwm to xmonad","August 15, 2015",""],
["switching_from_archlinux_to_gentoo","Switching from Archlinux to FreeBSD then Gentoo","August 29, 2015","archlinux,gentoo,bsd"],
["new_goodies","New goodies","September 03, 2015",""],
["nas_cloud","The home: NAS or cloud. Have both.","March 30, 2016",""],
["blog_converted2","Blog converted, chapter 01","April 05, 2016",""],
["blog_converted3","Blog converted, chapter 02","April 08, 2016",""],
["blog_converted4","Blog converted, chapter 03","April 10, 2016",""],
["tablet_cpr","Android pranks are not funny","April 13, 2016","bashing"],
["revup","Teaching an old dog new tricks","April 17, 2016",""],
["blog_converted5","Blog converted, chapter 04","April 20, 2016",""],
["search_form","Static Blog & search form, wutt ?","April 23, 2016",""],
["blog_converted6","Blog converted, chapter 05","April 24, 2016",""],
["blog_converted7","Blog converted, chapter 06","April 29, 2016",""],
["blog_converted8","Blog converted, chapter 07","May 2, 2016",""],
["sane_gentoo_tips","Sane Gentoo Tips","May 5, 2016","gentoo"],
["sane_gentoo_commands","Sane Gentoo Commands","May 7, 2016","gentoo"],
["sane_gentoo_repo","Sane Gentoo Repository","May 8, 2016","gentoo"],
["random_post3","Random post 3","May 19, 2016",""],
["run", "Decreased the blog loading time - again", "May 26, 2016",""],
["back_to_the_future", "Back to the future", "May 31, 2016",""],
["jblogfy", "My 3rd static generator", "June 01, 2016", ""],
["templating","Learn to love the ES6 native templating","June 04, 2016",""],
["bye_fox","Goodbye Firefox","June 07, 2016",""],
["git-serve","One-off Git server","June 09,2016",""],
["web-app","The offline blog app","June 13,2016","Bashing"],
["web-app2","Service Worker tips","June 16,2016",""],
["target-busy","umount target is busy","June 28,2016",""],
["sane_gentoo_repo2","Sane Gentoo Repository revisited","June 29,2016","gentoo"],
["pasta","My first urxvt extension","July 01,2016",""],
["man2pdf","Second urxvt extension","July 02,2016",""],
["mouse-pimp","Mouse donor","July 06,2016","gentoo"],
["thunar_plugin","Write a sane Thunar plugin","July 06,2016",""],
["hardware_tweaks","Replace some GUI apps with CLI","July 06,2016",""],
["crypto_funcs","Crypto funcs","July 06,2016","encrypt"],
["no_thunar_crash","Thunar rename crash","July 09,2016","bashing"],
["sane_cpu_flags","Sane Gentoo CPU flags","July 13, 2016","gentoo"],
["flash_format","Simple flash drive formatting","July 17,2016",""],
["same_snafu_3yrs_later","Same snafu 3yrs later","July 17,2016",""],
["dwm_bar_reborn","dwm-bar reborn","July 24,2016",""],
["kernel_misc","A few kernel tips","July 28,2016",""],
["merge_refusal","Git: Merge unrelated histories","March 11,2018",""],
["benchmark_terminal","Benchmark the terminal","March 11,2018",""],
["merge_two_repos","Merging the histories of repositories","March 11,2018",""],
["fastest_string_replacement","Fastest string replacement","March 13,2018",""],
["clone_all_github_repos","Clone all of your GitHub repos","March 21,2018",""],
["gentoo_misc","Gentoo misc","March 24,2018","gentoo"],
["nginx_serve","Simple web server","March 25,2018",""],
["imback","I'm back after missing for 6 years","August 06,2024",""],
["laptop","My Windows Laptop dual booting with Manjaro","August 06,2024","windows"],
["vscode","Setting up VSCode editor on Windows","August 06,2024","windows"],
["switching_from_xmonad_to_hellxcb","Switching from xmonad to hellxcb","August 07,2024","hellxcb"],
["blogstatus","The blog was unreachble for 5 years","August 08,2024",""],
["useful_make_flags","Using \"make\" flags to compile them","August 08,2024","clang"],
["using_arrays_in_c","Using struct array of functions","August 08,2024","clang"],
["using_many_args_to_function","Using many arguments to function","August 08,2024","clang"],
["token_concatenation","Token concatenation","August 09,2024","clang"],
["fixing_bug_in_hellxcb","Fixing a bug in hellxcb","August 09,2024","hellxcb"],
["screenfetch_c_contributions","Unmerged contributions to screenfetch-c","August 09,2024",""],
["hellxcb_cycle_mode","Cycling thru all hellxcb tiling modes","August 09,2024","hellxcb"],
["hellxcb_grid_bug","Fixed one more bug in hellxcb","August 10,2024","hellxcb"],
["hellxcb_move_resize_bug","Fixed anoter bug in hellxcb","August 11,2024","hellxcb"],
["doomy","A statusline written in x11","August 12,2024",""],
["hellxcb_count_all_workspaces","hellxcb - count all windows in all tags","August 13,2024","hellxcb"],
["argp_array","Use one array with argp.h","August 14,2024","clang"],
["argp_config","argp.h use config file to read from","August 14,2024","clang"],
["va_args","VA_ARGS and ... and how to use them","August 15,2024","clang"],
["archiso","Archiso to create custom .iso","August 18,2024","archlinux"],
["helllinux","My custom made Hell Linux distro","August 18,2024",""],
["debootstrap","The Debian debootstrap","August 19,2024",""],
["netbsd","The ghost lag in NetBSD","August 19,2024","bsd"],
["gentoo_install2","Back using Gentoo - install it","August 20,2024","gentoo"],
["skilcrypt","The skilcrypt","August 22,2024",""],
["ping_website","Ping and measure the roundtrip time","August 23,2024","clang"],
["reddit","Count the unread reddit notif.","August 23,2024","clang"],
["gmail","Count the unread emails","August 23,2024","clang"],
["github","Count the unread Github notif.","August 23,2024","clang"],
["kblayout","Query Xorg for the keyboard layout","August 23,2024","clang"],
["numcaps","Query Xorg for num caps scroll lock","August 23,2024","clang"],
["mousepercent","Query Xorg for the mouse speed","August 23,2024","clang"],
["retip","Get your public ip from C","August 23,2024","clang"],
["shufi","Generate random permutations ","August 23,2024","clang"],
["sortique","Sort inverse or reverse file","August 23,2024","clang"],
["basename","Basename in C","August 24,2024","clang"],
["cat","Cat in C","August 24,2024","clang"],
["dirname","Dirname in C","August 24,2024","clang"],
["false","False in C","August 24,2024","clang"],
["getavgload","Get average load in C","August 24,2024","clang"],
["head","Head in C","August 24,2024","clang"],
["hostname","Hostname in C","August 24,2024","clang"],
["tac","Tac in C","August 24,2024","clang"],
["tail","Tail in C","August 24,2024","clang"],
["true","True in C","August 24,2024","clang"],
["uname","Uname in C","August 24,2024","clang"],
["yes","Yes in C","August 24,2024","clang"],
["uptime","Uptime in C","August 24,2024","clang"],
["linux33","Happy 33rd birthday Linux","August 26,2024",""],
["urxvt_encrypt","Third urxvt extensions","August 27,2024",""],
["urxvt_man2pdf","Second urxvt extensions revisited","August 27,2024",""],
["expanding_luks","Expanding encrypted container","August 27,2024",""],
["pylogin","Login module for your app","August 28,2024",""],
["pacman_log_search","Pacman log searching","August 28,2024",""],
["blk","Backup like king","August 28,2024",""],
["konvert","The konvert program","August 28,2024",""],
["timeset-c","The timeset-c program","August 28,2024","clang"],
["hellphyze","The hellphyze program","August 28,2024",""],
["cpblogfy","cblogfy, pblogfy, bblogfy and cppblogfy","August 29,2024","clang"],
["yepstat","yepstat","August 30,2024",""],
["timeset","timeset-gui","August 30,2024",""],
["pshot","pshot","August 31,2024",""],
["hackzy","hackzy","September 01,2024","clang"],
["deploywebsite","Deploy a static website in GitHub","September 13,2024",""],
["gawk_extensions","Gawk extensions","October 01,2024","clang"],
["expand_luks","Expand LUKS encrypted file","November 01,2024","encrypt,luks"],
["gtkcalendar","Simple gtk calendar","December 01,2024",""],
["chattr","Locking files with chattr","January 02,2025",""],
["zip_unzip","Zip and unzip with python","February 02,2025",""],
["hellxcb_zero_windows","Fixed one more bug with hellxcb","March 01,2025","hellxcb"],
["hellxcb_border_colour","Changing the border colour of a window","April 01,2025","hellxcb"],
["pinkybar_changes","Color for the option and title","May 01,2025",""],
["while_read","Reading args from a pipe","June 01,2025",""],
["runtime_strings","Runtime formatted strings in C","July 01,2025","clang"],
["reference_wrapper","The reference wrapper","August 01,2025","c++"],
["download_diff","Download a git pull request","September 01,2025",""],
["2tattoos","I got 2 new tattoos","September 25,2025",""],
["grepc","grepc","November 01,2025","c++"],
["split_string","3 ways to split string in c/c++","November 01,2025","clang,c++"],
["split_string2","The way to catch wrong str splitting","November 01,2025","clang,c++"],
["altcase_strings","Creating different alt case strs","November 01,2025","c++"]

  ];

  w.metaPool = Object.freeze(metaPool);

  if ('serviceWorker' in navigator) {
    if (!!navigator.serviceWorker.controller) {
      navigator.serviceWorker.controller.postMessage(JSON.stringify(metaPool));
    }
  }
}(window));
